### ISSUE TITLE
Uncaught RuntimeException: SilverStripe\Assets\Image has no method SetWidth

### ISSUE THREAD

**Issue by silverstripe-elliot** [heyday/silverstripe-responsive-images#24]
I've tried installing the module with the settings recommended in README.md. When I try to call my image in a template I get the above message.

The sets fail because some methods are missing:
($HeroImage.ResponsiveSet1): has no method SetWidth
($HeroImage.ResponsiveSet2): has no method CroppedImage
($HeroImage.ResponsiveSet3): has no method PaddedImage

These methods were moved into a trait at some point in 4.x. Perhaps the issue is with the use of `hasMethod`? I'm not sure if there's a way to work around it

**Comment by stecman** [comment]
Hey @silverstripe-elliot, the readme needs to be updated to show SilverStripe 4's renamed resize methods (see [this PR](https://github.com/heyday/silverstripe-responsive-images/pull/23/files)).

`method` in the yaml config is used verbatim as a method name to call SilverStripe's image backend. You'll need to use [the same names you would in a template in SS4](https://docs.silverstripe.org/en/4/developer_guides/files/images/#manipulating-images-in-templates).

**Comment by silverstripe-elliot** [comment]
Thanks @stecman! 

[According to the changelog](https://docs.silverstripe.org/en/4/changelogs/4.0.0/) the methods have been renamed. 
* Image::SetWidth() to ScaleWidth()
* Image::PaddedImage() to Pad()
* Image::CroppedImage() to Fill()

I'll make a PR to update the docs . :)
