### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by cainbyrne-uleska** [heyday/silverstripe-responsive-images#35]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at  https://source-security.co.uk/65b9d0a9-6381-4311-b49e-c80fc99626be/

Thanks,
Chris

**Comment by stecman** [comment]
Sorry, this looks like an advertisement and doesn't contain any specific vulnerability information - it's just pointing out that `picturefill.js` uses regular expressions in a bunch of places and to "make sure that using a regular expression is safe here" along with other vague automed advice.  Reported as spam :disappointed:

**Comment by bendubuisson** [comment]
I reported it
