### ISSUE TITLE
Add extra classes from template

### ISSUE THREAD

**Issue by Firesphere** [heyday/silverstripe-responsive-images#38]
How can I add extra classes to the generated image tag?

**Comment by xini** [comment]
There are two ways:

You can add additional classes in the set definition:

```
Heyday\ResponsiveImages\ResponsiveImageExtension:
  sets:
    ResponsiveSet1:
      css_classes: your-custom-class
      arguments:
        ...
```

Or you can set the template it should use in yml:

```
Heyday\ResponsiveImages\ResponsiveImageExtension:
  sets:

    ResponsiveSet1:
      template: CustomResponsiveImageSet
      arguments:
        ...
```

and then in that template you can add additional classes:

```
<picture>
	<% loop $Sizes %>
		<source media="$Query" data-srcset="$Image.URL">
	<% end_loop %>
	<img src="$DefaultImage.URL" alt="$DefaultImage.AltText.ATT" width="$DefaultImage.Width" height="$DefaultImage.Height" class="your-custom-class<% if $ExtraClasses %> $ExtraClasses<% end_if %>">
</picture>
```

**Comment by Firesphere** [comment]
That's not exactly what I am after.

I was more looking to do `$Image.MyResponsiveSet.ExtraClasses('img-responsive')` from the template...

I think that behaviour, if possible, would be a good addition if it doesn't exist yet

**Comment by xini** [comment]
That definitely doesn't exist (yet). AFAIK that doesn't exist on normal images either?
